"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Plus, Server, Play, Square, RotateCcw, Settings2, X } from "lucide-react";

type ServerItem={id:string;name:string;game:string;status:string;region:string;ram_mb:number;cpu_cores:number;disk_gb:number;port:number|null;created_at:string};
const games=["Valheim","Minecraft","Terraria","Rust","CS2","Palworld"];
const statusLabel:Record<string,string>={provisioning:"Создаётся",running:"Запущен",stopped:"Остановлен",restarting:"Перезапуск",error:"Ошибка"};

export default function ServersManager(){
 const [servers,setServers]=useState<ServerItem[]>([]); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState("");
 const [form,setForm]=useState({name:"Мой сервер",game:"Valheim",ram_mb:2048,cpu_cores:2,disk_gb:20,region:"eu-central"});
 async function load(){setLoading(true);try{const r=await fetch("/api/servers",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setServers(d.servers||[]);}catch(e){setError(e instanceof Error?e.message:"Ошибка загрузки");}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(){setBusy("create");setError("");try{const r=await fetch("/api/servers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);setOpen(false);await load();}catch(e){setError(e instanceof Error?e.message:"Не удалось создать сервер")}finally{setBusy(null)}}
 async function action(id:string,action:string){setBusy(id+action);setError("");try{const r=await fetch(`/api/servers/${id}/action`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:"Ошибка управления")}finally{setBusy(null)}}
 return <div>
  <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-zinc-600">GameHost</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Мои серверы</h1><p className="mt-2 text-sm text-zinc-600">Создавайте и управляйте игровыми серверами из одной панели.</p></div><button onClick={()=>setOpen(true)} className="flex w-fit items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-medium text-black"><Plus size={16}/>Создать сервер</button></div>
  {error&&<div className="mt-5 rounded-xl border border-zinc-700 bg-zinc-900 p-3 text-sm text-zinc-300">{error}</div>}
  {loading?<div className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-950 p-10 text-center text-sm text-zinc-600">Загрузка серверов...</div>:servers.length===0?<div className="mt-8 rounded-2xl border border-dashed border-zinc-800 bg-zinc-950/60 p-12 text-center"><Server className="mx-auto text-zinc-700" size={32}/><h2 className="mt-4 font-medium">Серверов пока нет</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-600">Создай первый сервер. Если нода Docker ещё не подключена, сервер сохранится как заявка на создание.</p><button onClick={()=>setOpen(true)} className="mt-6 rounded-xl border border-zinc-700 px-4 py-2.5 text-sm hover:bg-zinc-900">Создать первый сервер</button></div>:<div className="mt-8 grid gap-4 lg:grid-cols-2">{servers.map(s=><motion.div key={s.id} whileHover={{y:-3}} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-6"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-zinc-900 text-zinc-300"><Server size={20}/></span><div><h2 className="font-medium">{s.name}</h2><p className="mt-1 text-xs text-zinc-600">{s.game} · {s.region}</p></div></div><span className={`rounded-full border px-2.5 py-1 text-[11px] ${s.status==="running"?"border-white/15 bg-white/[.06] text-white":"border-zinc-800 bg-zinc-900 text-zinc-500"}`}>{statusLabel[s.status]||s.status}</span></div><div className="mt-6 grid grid-cols-3 gap-2">{[["CPU",`${s.cpu_cores} vCPU`],["RAM",`${s.ram_mb/1024} GB`],["NVMe",`${s.disk_gb} GB`]].map(([a,b])=><div key={a} className="rounded-xl border border-zinc-900 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-widest text-zinc-700">{a}</p><p className="mt-1 text-sm">{b}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/dashboard/servers/${s.id}`} className="flex items-center gap-2 rounded-lg border border-zinc-800 px-3 py-2 text-xs hover:bg-zinc-900"><Settings2 size={14}/>Панель</Link>{s.status==="running"?<button disabled={busy===s.id+"stop"} onClick={()=>action(s.id,"stop")} className="flex items-center gap-2 rounded-lg border border-zinc-800 px-3 py-2 text-xs hover:bg-zinc-900"><Square size={13}/>Стоп</button>:<button disabled={busy===s.id+"start"} onClick={()=>action(s.id,"start")} className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-xs font-medium text-black"><Play size={13}/>Запуск</button>}<button disabled={busy===s.id+"restart"} onClick={()=>action(s.id,"restart")} className="flex items-center gap-2 rounded-lg border border-zinc-800 px-3 py-2 text-xs hover:bg-zinc-900"><RotateCcw size={13}/>Рестарт</button></div></motion.div>)}</div>}
  {open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl border border-zinc-800 bg-zinc-950 p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Создать игровой сервер</h2><p className="mt-1 text-xs text-zinc-600">Ресурсы можно изменить позже.</p></div><button onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="mt-6 space-y-4"><label className="block text-sm">Название<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl border border-zinc-800 bg-black/30 px-4 py-3 outline-none focus:border-zinc-500"/></label><label className="block text-sm">Игра<select value={form.game} onChange={e=>setForm({...form,game:e.target.value})} className="mt-2 w-full rounded-xl border border-zinc-800 bg-black/30 px-4 py-3 outline-none">{games.map(g=><option key={g}>{g}</option>)}</select></label><div className="grid grid-cols-3 gap-3"><label className="text-sm">RAM<select value={form.ram_mb} onChange={e=>setForm({...form,ram_mb:Number(e.target.value)})} className="mt-2 w-full rounded-xl border border-zinc-800 bg-black/30 px-3 py-3">{[1024,2048,4096,8192,16384].map(v=><option key={v} value={v}>{v/1024} GB</option>)}</select></label><label className="text-sm">CPU<select value={form.cpu_cores} onChange={e=>setForm({...form,cpu_cores:Number(e.target.value)})} className="mt-2 w-full rounded-xl border border-zinc-800 bg-black/30 px-3 py-3">{[1,2,4,6,8].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label className="text-sm">Диск<select value={form.disk_gb} onChange={e=>setForm({...form,disk_gb:Number(e.target.value)})} className="mt-2 w-full rounded-xl border border-zinc-800 bg-black/30 px-3 py-3">{[10,20,40,80,160].map(v=><option key={v} value={v}>{v} GB</option>)}</select></label></div><button disabled={!!busy} onClick={create} className="w-full rounded-xl bg-white py-3 text-sm font-medium text-black disabled:opacity-50">{busy==="create"?"Создание...":"Создать сервер"}</button></div></div></div>}
 </div>
}
