"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, CheckCircle2, Eye, EyeOff, Lock, Mail, User, Loader2, ShieldCheck } from "lucide-react";
import { AuthCard } from "@/components/AuthCard";

const input = "h-12 w-full rounded-xl border border-zinc-800 bg-zinc-900/65 text-sm text-white outline-none transition placeholder:text-zinc-600 focus:border-zinc-700 input-glow focus:ring-2 focus:ring-indigo-500/10";
const item = { hidden:{opacity:0,y:10}, show:{opacity:1,y:0} };

export default function RegisterPage(){
 const [username,setUsername]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [focused,setFocused]=useState<string|null>(null);
 useEffect(()=>{fetch("/api/auth/me",{cache:"no-store"}).then(r=>{if(r.ok) window.location.replace("/dashboard")}).catch(()=>{})},[]);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(!username||!email||!password||!confirm)return setError("Заполните все поля.");if(password!==confirm)return setError("Пароли не совпадают.");setLoading(true);try{const r=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,email,password})});const d=await r.json();if(!r.ok)return setError(d.error||"Не удалось создать аккаунт.");window.location.href="/dashboard"}catch{setError("Не удалось связаться с сервером.")}finally{setLoading(false)}}
 const field=(label:string,icon:React.ReactNode,value:string,setter:(v:string)=>void,placeholder:string,type="text",name="")=><motion.div variants={item}><label className="mb-2 block text-sm text-zinc-400">{label}</label><div className="relative"><motion.span animate={{color:focused===name?"#818cf8":"#52525b",scale:focused===name?1.08:1}} className="absolute left-3 top-1/2 -translate-y-1/2">{icon}</motion.span><input className={`${input} pl-10 pr-10`} type={type} value={value} onChange={e=>setter(e.target.value)} onFocus={()=>setFocused(name)} onBlur={()=>setFocused(null)} placeholder={placeholder}/><AnimatePresence>{value&&<motion.span initial={{opacity:0,scale:.7}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.7}} className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-300"><CheckCircle2 size={16}/></motion.span>}</AnimatePresence></div></motion.div>;
 return <AuthCard title="Создайте аккаунт" subtitle="Начните управлять игровыми серверами"><motion.form onSubmit={submit} initial="hidden" animate="show" variants={{hidden:{},show:{transition:{staggerChildren:.06,delayChildren:.12}}}} className="space-y-4">
   {field("Имя пользователя",<User size={18}/>,username,setUsername,"Например: Dmytro","text","username")}
   {field("Email",<Mail size={18}/>,email,setEmail,"you@example.com","email","email")}
   <motion.div variants={item}><label className="mb-2 block text-sm text-zinc-400">Пароль</label><div className="relative"><Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600" size={18}/><input className={`${input} pl-10 pr-12`} type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} onFocus={()=>setFocused("password")} onBlur={()=>setFocused(null)} placeholder="Минимум 8 символов" autoComplete="new-password"/><motion.button whileTap={{scale:.85}} type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-600 hover:text-zinc-300">{show?<EyeOff size={18}/>:<Eye size={18}/>}</motion.button></div><div className="mt-2 flex items-center gap-2 text-[11px] text-zinc-600"><ShieldCheck size={13}/> Пароль хранится в виде защищённого хеша</div></motion.div>
   <motion.div variants={item}><label className="mb-2 block text-sm text-zinc-400">Повторите пароль</label><div className="relative"><Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600" size={18}/><input className={`${input} pl-10 pr-4`} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Повторите пароль" autoComplete="new-password"/></div></motion.div>
   <AnimatePresence>{error&&<motion.div initial={{opacity:0,height:0,y:-5}} animate={{opacity:1,height:"auto",y:0}} exit={{opacity:0,height:0,y:-5}} className="overflow-hidden rounded-xl border border-red-900/50 bg-red-950/30 px-4 py-3 text-sm text-red-400">{error}</motion.div>}</AnimatePresence>
   <motion.button variants={item} whileHover={{y:-2,scale:1.005}} whileTap={{scale:.985}} disabled={loading} className="btn-shine group relative flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-medium text-black disabled:opacity-60">{loading?<><Loader2 size={17} className="animate-spin"/>Создание...</>:<>Создать аккаунт<ArrowRight size={17} className="transition-transform duration-300 group-hover:translate-x-1"/></>}</motion.button>
 </motion.form><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.55}} className="mt-7 border-t border-zinc-800/80 pt-6 text-center text-sm text-zinc-500">Уже есть аккаунт? <Link href="/login" className="font-medium text-zinc-300 hover:text-zinc-300">Войти</Link></motion.div></AuthCard>
}
