import Link from "next/link";
import { HomeNav } from "@/components/HomeNav";
import { ArrowRight, Gamepad2, Globe2, Users } from "lucide-react";

const games = [
  { name: "Valheim", genre: "Survival · Co-op", players: "1–10+", color: "from-white/10 to-white/[.02]", desc: "Сервер для выживания, строительства и совместного прохождения мира с друзьями.", tags: ["Бэкапы", "Моды", "Консоль"] },
  { name: "Minecraft", genre: "Sandbox · Survival", players: "1–50+", color: "from-white/10 to-lime-500/5", desc: "Гибкий сервер для vanilla, modded и популярных сборок с управлением файлами и настройками.", tags: ["Java", "Моды", "Плагины"] },
  { name: "Terraria", genre: "Sandbox · Adventure", players: "1–16+", color: "from-sky-500/20 to-blue-500/5", desc: "Лёгкий игровой сервер для совместных приключений, строительства и исследования мира.", tags: ["World files", "Бэкапы", "Консоль"] },
  { name: "Rust", genre: "Survival · PvP", players: "1–100+", color: "from-orange-500/20 to-red-500/5", desc: "Высокопроизводительная конфигурация для серверов Rust с контролем ресурсов и настройками.", tags: ["RCON", "Бэкапы", "Мониторинг"] },
  { name: "CS2", genre: "FPS · Competitive", players: "10–64", color: "from-amber-500/20 to-yellow-500/5", desc: "Игровые инстансы Counter-Strike 2 с быстрым запуском и подготовкой к кастомным конфигурациям.", tags: ["Console", "Config", "Monitoring"] },
  { name: "Palworld", genre: "Survival · Open World", players: "1–32+", color: "from-violet-500/20 to-fuchsia-500/5", desc: "Отдельный игровой сервер для кооперативного мира с резервными копиями и управлением ресурсами.", tags: ["Бэкапы", "Консоль", "NVMe"] },
];

export default function GamesPage() {
  return <main className="min-h-screen overflow-hidden bg-[#050507] text-white"><div className="pointer-events-none fixed inset-0"><div className="hero-orb absolute left-1/2 top-[-300px] h-[650px] w-[650px] -translate-x-1/2 rounded-full bg-white/[.04] blur-[150px]"/><div className="grid-bg absolute inset-0 opacity-60"/></div><HomeNav/>
    <section className="relative z-10 mx-auto max-w-7xl px-6 pb-16 pt-20 lg:px-8 lg:pt-28"><div className="max-w-3xl animate-fade-up"><p className="text-xs uppercase tracking-[.22em] text-zinc-300/70">Каталог игр</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.04em] sm:text-7xl">Выбери свой мир.</h1><p className="mt-6 text-lg leading-8 text-zinc-500">Здесь собраны игровые шаблоны GameHost. Для каждой игры мы готовим отдельную конфигурацию, чтобы запуск и дальнейшее управление были максимально простыми.</p></div></section>
    <section className="relative z-10 mx-auto max-w-7xl px-6 pb-28 lg:px-8"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{games.map((game,i)=><article key={game.name} className={`premium-border glass hover-lift animate-fade-up stagger-${(i%4)+1} overflow-hidden rounded-3xl`}><div className={`relative h-40 bg-gradient-to-br ${game.color}`}><div className="grid-bg absolute inset-0 opacity-30"/><div className="absolute bottom-5 left-5 flex h-12 w-12 items-center justify-center rounded-2xl border border-white/10 bg-black/30 backdrop-blur-xl"><Gamepad2 size={22}/></div><div className="absolute right-5 top-5 rounded-full border border-white/10 bg-black/25 px-3 py-1.5 text-[11px] text-zinc-300 backdrop-blur">GameHost template</div></div><div className="p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{game.name}</h2><p className="mt-1 text-xs text-zinc-600">{game.genre}</p></div><span className="flex items-center gap-1.5 text-xs text-zinc-500"><Users size={14}/>{game.players}</span></div><p className="mt-5 text-sm leading-7 text-zinc-500">{game.desc}</p><div className="mt-5 flex flex-wrap gap-2">{game.tags.map(tag=><span key={tag} className="rounded-lg border border-zinc-800 bg-zinc-950 px-2.5 py-1.5 text-[11px] text-zinc-500">{tag}</span>)}</div><Link href="/register" className="btn-shine mt-6 flex items-center justify-center gap-2 rounded-xl border border-zinc-800 bg-zinc-950 py-3 text-sm text-zinc-300 transition hover:border-zinc-700 hover:text-white">Создать сервер <ArrowRight size={15}/></Link></div></article>)}</div></section>
    <section className="relative z-10 border-t border-zinc-900 py-24"><div className="mx-auto max-w-4xl px-6 text-center"><Globe2 className="mx-auto text-zinc-500" size={25}/><h2 className="mt-5 text-3xl font-semibold">Больше игр будет добавляться постепенно.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-zinc-500">Архитектура GameHost рассчитана на игровые шаблоны: отдельная конфигурация, Docker-окружение, порты, ресурсы и управление из одной панели.</p><Link href="/register" className="btn-shine mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-medium text-black">Начать с GameHost <ArrowRight size={16}/></Link></div></section>
  </main>;
}
