import Link from "next/link";
import { HomeNav } from "@/components/HomeNav";
import { ArrowRight, Check, Cpu, HardDrive, Headphones, ShieldCheck, Zap } from "lucide-react";

const plans = [
  { name: "Starter", price: "€3.99", desc: "Для небольших серверов и игры с друзьями.", ram: "2 GB", cpu: "1 vCPU", disk: "20 GB NVMe", featured: false },
  { name: "Standard", price: "€7.99", desc: "Сбалансированный вариант для регулярной игры.", ram: "4 GB", cpu: "2 vCPU", disk: "50 GB NVMe", featured: true },
  { name: "Premium", price: "€14.99", desc: "Больше ресурсов для крупных миров и модов.", ram: "8 GB", cpu: "4 vCPU", disk: "100 GB NVMe", featured: false },
];

const common = ["DDoS-защищённая инфраструктура", "Панель управления GameHost", "Управление сервером 24/7", "Резервные копии", "Мониторинг ресурсов", "Доступ к консоли"];

export default function PricingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#050507] text-white"><div className="pointer-events-none fixed inset-0"><div className="hero-orb absolute left-1/2 top-[-300px] h-[650px] w-[650px] -translate-x-1/2 rounded-full bg-white/[.04] blur-[150px]"/><div className="hero-orb-reverse absolute right-[-250px] top-[45%] h-[520px] w-[520px] rounded-full bg-white/[.03] blur-[160px]"/><div className="grid-bg absolute inset-0 opacity-60"/></div><HomeNav/>
    <section className="relative z-10 mx-auto max-w-7xl px-6 pb-14 pt-20 text-center lg:px-8 lg:pt-28"><div className="animate-fade-up mx-auto max-w-3xl"><p className="text-xs uppercase tracking-[.22em] text-zinc-300/70">Тарифы GameHost</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.04em] sm:text-7xl">Плати за ресурсы,<br/><span className="text-zinc-600">а не за сложность.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-zinc-500">Выбери конфигурацию под свою игру. Все планы получают доступ к одной панели управления, а ресурсы отличаются в зависимости от тарифа.</p></div></section>
    <section className="relative z-10 mx-auto max-w-6xl px-6 pb-28 lg:px-8"><div className="grid gap-4 lg:grid-cols-3">{plans.map((plan,i)=><article key={plan.name} className={`premium-border hover-lift animate-fade-up stagger-${i+1} relative rounded-3xl border p-7 ${plan.featured?"border-zinc-600 bg-zinc-900/75 shadow-[0_30px_100px_rgba(99,102,241,.1)]":"border-zinc-800 bg-zinc-950/75"}`}>{plan.featured&&<div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full border border-zinc-700 bg-zinc-900 px-3 py-1 text-[10px] uppercase tracking-[.15em] text-zinc-300">Популярный</div>}<p className="text-sm font-medium">{plan.name}</p><p className="mt-2 text-xs leading-6 text-zinc-600">{plan.desc}</p><div className="mt-7"><span className="text-4xl font-semibold">{plan.price}</span><span className="text-sm text-zinc-600"> / мес.</span></div><div className="mt-7 space-y-3 border-y border-zinc-900 py-6 text-sm">{[[Cpu,plan.cpu],[Zap,plan.ram],[HardDrive,plan.disk]].map(([Icon,text])=>{const I=Icon as typeof Cpu;return <div key={text as string} className="flex items-center gap-3 text-zinc-300"><I size={16} className="text-zinc-600"/>{text as string}</div>})}</div><Link href="/register" className={`btn-shine mt-6 flex items-center justify-center gap-2 rounded-xl py-3.5 text-sm font-medium transition hover:-translate-y-0.5 ${plan.featured?"bg-white text-black hover:bg-zinc-200":"border border-zinc-800 bg-zinc-950 text-zinc-300 hover:border-zinc-700 hover:text-white"}`}>Выбрать тариф <ArrowRight size={15}/></Link></article>)}</div>
      <div className="mt-8 grid gap-3 rounded-3xl border border-zinc-900 bg-zinc-950/50 p-6 sm:grid-cols-2 lg:grid-cols-3">{common.map(item=><div key={item} className="flex items-center gap-3 text-sm text-zinc-500"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-zinc-900 text-zinc-400"><Check size={14}/></span>{item}</div>)}</div></section>
    <section className="relative z-10 border-t border-zinc-900 py-24"><div className="mx-auto max-w-5xl px-6"><div className="grid gap-4 md:grid-cols-3"><div className="glass rounded-2xl p-6"><ShieldCheck className="text-zinc-400" size={20}/><h3 className="mt-4 font-medium">Безопасность</h3><p className="mt-2 text-sm leading-6 text-zinc-600">Защищённая авторизация и изоляция окружений серверов.</p></div><div className="glass rounded-2xl p-6"><Headphones className="text-zinc-400" size={20}/><h3 className="mt-4 font-medium">Поддержка</h3><p className="mt-2 text-sm leading-6 text-zinc-600">Панель строится так, чтобы основные действия были понятны без технических знаний.</p></div><div className="glass rounded-2xl p-6"><Zap className="text-zinc-400" size={20}/><h3 className="mt-4 font-medium">Масштабирование</h3><p className="mt-2 text-sm leading-6 text-zinc-600">В будущем ресурсы и игровые ноды можно будет расширять вместе с проектом.</p></div></div></div></section>
  </main>;
}
